/**
 * SPDX-License-Identifier: BSD-3-Clause
 * Copyright (c) 2026 Anthony Lee Stark. All rights reserved.
 */

#pragma once

#include "nex/base/namespace.h"
#include "nex/base/types.h"
#include "nex/base/logging.h"
#include "nex/base/coordinators.h"
#include "nex/base/wrappers.h"
#include "src/infrastructure/logging/record.h"

NEX_LAYER_NAMESPACE_BEGIN(logging)

/**
 * @enum LogCommandType
 * @brief Defines the types of commands that can be issued to the logging system.
 */
enum class LogCommandType {
    Record,
    Flush,
    Shutdown
};

/**
 * @struct LogCommand
 * @brief  Records log entries generated by the application or system.
 */
struct NEX_INTERNAL RecordCommand {
    LogRecord record;   // The log record to be processed.
};

/**
 * @struct FlushCommand
 * @brief  Signals the logging system to flush any buffered log entries to their respective sinks.
 */
struct NEX_INTERNAL FlushCommand {
    BinarySemaphore* completion;  // Optional semaphore to signal when the flush operation is complete.
};

/**
 * @struct ShutdownCommand
 * @brief  Requests the logging system to perform a graceful shutdown, ensuring all pending log entries are processed.
 */
struct NEX_INTERNAL ShutdownCommand {
    BinarySemaphore* completion;  // Optional semaphore to signal when the shutdown operation is complete.
};

/**
 * @typedef WorkerCommand
 * @brief   A variant type that can hold any of the defined log command types.
 */
using WorkerCommand =
    Variant<
        RecordCommand,
        FlushCommand,
        ShutdownCommand
    >;

NEX_LAYER_NAMESPACE_END(logging)
