/**
 * SPDX-License-Identifier: BSD-3-Clause
 * Copyright (c) 2026 Anthony Lee Stark. All rights reserved.
 */

#pragma once

#include "nex/base/namespace.h"
#include "nex/base/types.h"
#include "nex/base/casts.h"
#include "nex/base/logging.h"
#include "nex/base/wrappers.h"  // For using Variant
#include "nex/core/adapters/queue.h"
#include "nex/infrastructure/logging/config.h"
#include "src/infrastructure/logging/record.h"

NEX_LAYER_NAMESPACE_BEGIN(logging)

/**
 * @class  LogQueue
 * @brief  A thread-safe queue for managing log records in the logging system.
 * 
 * @details
 * This class provides a simple interface for enqueuing and dequeuing log records. It is designed to be used
 * by the logging system to manage log entries generated by different threads and processes. The underlying
 * queue is implemented using the Queue adapter, which allows for flexible container types.
 */
class NEX_INTERNAL LogQueue {
public:
    // Type of items stored in the queue
    using QueueItem = Variant<LogRecord>;

    // The underlying queue type
    using QueueType = Queue<LogRecord>;

    /**
     * @brief Constructs a LogQueue with an optional maximum capacity.
     * @param maxCapacity The maximum number of log records the queue can hold.
     * @param overflowPolicy The policy to apply when the queue reaches its maximum capacity.
     */
    explicit LogQueue(
        usize maxCapacity = DefaultLogQueueCapacity,
        QueueOverflowPolicy overflowPolicy = QueueOverflowPolicy::DropOldest)
            : queue_(), overflowPolicy_(overflowPolicy)
    {
        if (maxCapacity < MinLogQueueCapacity) {
            maxCapacity_ = MinLogQueueCapacity;
        } else if (maxCapacity > MaxLogQueueCapacity) {
            maxCapacity_ = MaxLogQueueCapacity;
        } else {
            maxCapacity_ = maxCapacity;
        }
    }

    /**
     * @brief Enqueue a log record into the queue.
     * @param record The log record to enqueue.
     * @return The new size of the queue after the log record has been added.
     */
    usize enqueue(LogRecord&& record) {
        if (queue_.size() >= maxCapacity_) {
            switch (overflowPolicy_) {
                case QueueOverflowPolicy::Block:
                    // In a real implementation, you would block until space is available.
                    // For this example, we will just drop the log record.
                    return queue_.size();
                case QueueOverflowPolicy::DropNewest:
                    // Drop the newest log record (the one being added).
                    return queue_.size();
                case QueueOverflowPolicy::DropOldest:
                    // Drop the oldest log record to make space for the new one.
                    if (!queue_.empty()) {
                        queue_.pop();
                    }
                    break;
                case QueueOverflowPolicy::Grow:
                    // Allow the queue to grow beyond its initial capacity.
                    break;
            }
        } else {
            // If the queue is not full, simply add the new log record
            queue_.push(NEX_FORWARD<LogRecord>(record));
        }
        return queue_.size();
    }

    /**
     * @brief Dequeue a log record from the queue.
     * @param record The log record to store the dequeued value.
     * @return true if a log record was successfully dequeued, false if the queue was empty.
     */
    bool dequeue(LogRecord& record) {
        if (queue_.empty()) {
            return false;
        }
        record = NEX_MOVE(queue_.front());
        queue_.pop();
        return true;
    }

    /**
     * @brief Evaluates whether the logging queue is empty.
     * @return true if the queue is empty, false otherwise.
     */
    constexpr bool empty() const noexcept { return queue_.empty(); }

    /**
     * @brief Returns the number of log records currently in the queue.
     * @return The size of the queue.
     */
    constexpr usize size() const noexcept { return queue_.size(); }

    /**
     * @brief Returns the maximum capacity of the logging queue.
     * @return The maximum number of log records the queue can hold.
     */
    constexpr usize capacity() const noexcept { return maxCapacity_; }

private:
    // The actual underlying queue that stores the log records.
    QueueType queue_;

    // Maximum capacity of the queue (if applicable)
    usize maxCapacity_;

    // Policy for handling queue overflow situations
    const QueueOverflowPolicy overflowPolicy_;
};

NEX_LAYER_NAMESPACE_END(logging)
